feat: inform that a new version is available
RoadTripMoustache/kana_to_kanji pull request #255
Opened 2024-05-18 01:42 UTC by Adaendra

## 📖 Description
Implementation of upgrader to inform the user that a new version of the application is out and help them to get it easily.

### ⁉️ Related Issues
closes: #29 

### 🖼️ Screenshots:

<details>
    <summary>Use case</summary> 

[issue_29.webm](https://github.com/RoadTripMoustache/kana_to_kanji/assets/36586573/30a2f1a0-6956-4eff-bfbf-2623387e6f18)

</details>

### 🧪 How to test the change?
- Add the following code somewhere in the app
```dart
class MyUpgrader extends Upgrader {
  MyUpgrader({super.debugLogging, super.storeController});

}
```
- Add the following code in the `build` method of `prepare_quiz-view.dart`
```dart
final upgrader = MyUpgrader(
      debugLogging: true,
      storeController: UpgraderStoreController(
        onAndroid: () => UpgraderAppcastStore(
            appcastURL:
                'https://raw.githubusercontent.com/larryaasen/upgrader/master/test/testappcast.xml'),
        oniOS: () => UpgraderAppcastStore(
            appcastURL:
                'https://raw.githubusercontent.com/larryaasen/upgrader/master/test/testappcast.xml'),
      ),
    );
```
- Add `upgrader = upgrader` in the `AppSnackBarUpgrader` declaration  in the `build` method of `prepare_quiz-view.dart`
- Open the application

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] I have added/updated tests.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`.

2024-05-18 15:09 UTC, apomalyn commented on localization/en.arb
> +  "snackbar_update_version_message": "Version {version} is now available !",
Pour facilité la compréhension du message mieux vaut: 
```suggestion
  "snackbar_update_version_message": "A new version is available !",
```

2024-05-18 15:09 UTC, apomalyn commented on localization/fr.arb
> +  "snackbar_update_version_message": "La version {version} est disponible !",
```suggestion
  "snackbar_update_version_message": "Une nouvelle version est disponible !",
```

2024-05-18 15:14 UTC, apomalyn requested changes

2024-05-18 15:14 UTC, apomalyn commented on lib/src/quiz/prepare/prepare_quiz_view.dart
> +    return AppSnackBarUpgrader(
Je le mettrais autour de `KanaToKanjiApp` pour permettre de l'avoir quelque soit le point d'entrée dans l'app. Voir la [doc](https://pub.dev/packages/upgrader#go-router) pour GoRouter

2024-05-19 21:06 UTC, Adaendra commented on lib/src/quiz/prepare/prepare_quiz_view.dart
> +    return AppSnackBarUpgrader(
Changement fait

2024-05-19 21:37 UTC, apomalyn submitted a review, later dismissed
Une dernière petite modification mais tu as mon approbation pour la merge quand tu l'as fait!

2024-05-19 21:37 UTC, apomalyn commented on localization/en.arb
> +  "snackbar_update_version_message": "A new version is available !"
En anglais, il n'y a pas d'espace avec un point d'exclamation ou d'interrogation 
```suggestion
  "snackbar_update_version_message": "A new version is available!"
```

2024-05-21 02:15 UTC, apomalyn approved these changes

2024-05-21 02:15 UTC, merged